version: "3"

services:
  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  app:
    build: .
    ports:
      - "8081:8081"
